# Generated by Django 4.2.16 on 2025-02-06 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_date_of_birth_customuser_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={"ordering": ["-added_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.AddField(
            model_name="favorite",
            name="added_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Accepted", "Accepted")],
                default="Pending",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="user1",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="user2",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "country_code")},
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(
                fields=("user1", "user2"), name="unique_friendship"
            ),
        ),
        migrations.RemoveField(
            model_name="friendship",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="friendship",
            name="to_user",
        ),
    ]
