# Generated by Django 4.2.16 on 2025-03-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_blogpost_category_like_comment_blogpost_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
